config/routes.rb
Footprints::Application.routes.draw do



devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
get 'users/sign_in' => 'sessions#oauth_signin', :as => :oauth_signin
get 'auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2', :as => :new_session


 
 delete 'sessions/destroy', :as => :sessions_destroy
  
  
  
  
  get "applicants" => 'applicants#index'
  get "applicants/unassigned" => 'applicants#unassigned', as: 'unassigned_applicants'
  get "applicants/new" => 'applicants#new', as: 'new_applicant'
  post "applicants/new" => 'applicants#create'
  post "applicants/submit" => 'applicants#submit'
  get "applicants/:id/deny_application" => "applicants#deny_application", as: "deny_application"
  get "applicants/:id/assign_craftsman" => "applicants#assign_craftsman", as: "assign_craftsman"
  get "applicants/:id/hire" => 'applicants#hire', as: "hire_applicant"
  post "update_state/:id" => 'applicants#update_state', :as => 'update_state'
  post "make_decision/:id" => 'applicants#make_decision', :as => 'make_decision'
  get "applicants/:id", to: 'applicants#show', as: 'applicant'
  post "applicants/:id" => 'applicants#update'
  get "applicants/:id/edit",to: 'applicants#edit', as: 'edit_applicant'
  delete "applicants/:id" => 'applicants#destroy'
  get "applicants/:id/offer_letter" => 'applicants#offer_letter'
  get "applicants/:id/offer_letter_form" => 'applicants#offer_letter_form'
  get "applicants/:id/onboarding_letters" => 'applicants#onboarding_letters'
  post "applicants/:id/update_employment_dates" => 'applicants#update_employment_dates'
  patch "applicants/:id/unarchive" => 'applicants#unarchive', as: "unarchive_applicant"

  get 'users/:id', to: 'users#show', as: 'user'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  post 'users/:id', to: 'users#update'

  post "messages/create" => 'messages#create'

  post "notes/create" => "notes#create", as: 'notes'
  get "notes/:id/edit" => "notes#edit", as: 'note'
  patch "notes/update/:id" => "notes#update", as: 'note_update'

  get "analytics" => "analytics#index"
  get "profile" => "craftsmen#profile", as: 'profile'
  get "craftsmen/seeking" => "craftsmen#seeking", as: 'craftsmen'
  put "craftsman/update" => "craftsmen#update"

  get "search_suggestions" => 'search_suggestions#index'
  get "craftsman_suggestions" => 'search_suggestions#craftsman_suggestions'
  get "dashboard/confirm_applicant_assignment" => "dashboard#confirm_applicant_assignment", as: 'confirm_applicant_assignment'
  get "dashboard/decline_applicant_assignment" => "dashboard#decline_applicant_assignment", as: 'decline_applicant_assignment'
  post "dashboard/decline_all_applicants" => "dashboard#decline_all_applicants", as: 'decline_all_applicants'

  get "templates" => "dashboard#email_templates", as: "templates"

  get "admin" => "admin#index", as: "admin"

  get "salaries/edit" => "salaries#edit", as: "salaries"
  post "salaries/create_monthly" => "salaries#create_monthly"
  post "salaries/create_annual" => "salaries#create_annual"
  post "salaries/update" => "salaries#update"
  delete "salaries/:id" => "salaries#destroy", as: "destroy_salary"

  get "reporting" => "reporting#index", as: "reporting"
  
  get "apprentices" => "apprentices#index", as: "apprentices"
  get "apprentices/:id" => "apprentices#edit"
  put "apprentices/:id" => "apprentices#update"

  root :to => "dashboard#index"
end

app/controllers/salaries_controller.rb
require './lib/salaries/salary_presenter'
require './lib/salaries/salary_updater'
require './lib/repository'

class SalariesController < ApplicationController
  before_filter :require_admin

  def edit
    monthly_salaries = Footprints::Repository.monthly_apprentice_salary.all
    annual_salaries = Footprints::Repository.annual_starting_craftsman_salary.all
    @salary_presenter = SalaryPresenter.new(monthly_salaries, annual_salaries, params)
    render "salary_update_form"
  end

  def update
    SalaryUpdater.new(params).update
    redirect_to "/salaries/edit", :notice => "Successfully updated salaries."
  rescue Exception => e
    flash[:error] = [e.message]
    redirect_to "/salaries/edit"
  end

  def create_monthly
    SalaryUpdater.new(monthly_salary_params).create_monthly
    redirect_to("/salaries/edit", :notice => "Successfully created salary.")
  rescue StandardError => e
    flash[:error] = [e.message]
    redirect_to "/salaries/edit"
  end

  def destroy
    SalaryUpdater.new(params).destroy
    redirect_to salaries_path, :notice => "Successfully deleted salary."
  end

  private

  def monthly_salary_params
    params.require(:salary).permit(:duration, :location, :amount)
  end

  def annual_salary_params
    params.require(:salary).permit(:location, :amount)
  end
end

app/views/salaries/salary_update_form.html.erb
<div class="container salaries">
  <div class="row">
    <div class="column one-third">
      <h1>Add New Monthly Salary</h1>
      <form action="/salaries/create_monthly" method="POST" class="salary-form">
        <div class="form-column">
          <p>
          <label for="salary[duration]">Duration</label>
          <input type="text" name="salary[duration]" />
          </p>
          <p>
          <label for="salary[location]">Location</label>
          <select name="salary[location]" class="dropdown">
            <% @salary_presenter.locations.each do |location| %>
              <option value="<%= @salary_presenter.current_city %>"><%= location %></option>
            <% end %>
          </select>
          </p>
          <p>
          <label for="salary[amount]" >Amount</label>
          <input type="text" name="salary[amount]" />
          </p>
          <div class="row">
            <input type="submit" id="add-monthly-salary" class="button primary" value="Add Monthly Salary">
          </div>
        </div>
      </form>
    </div>

    <div class="column two-thirds">
      <%= form_for :salary_presenter, url: salaries_path, method: :get, html: { :class => 'drop-down-filter' } do |f| %>
        <%= select_tag(:city, options_for_select([['Filter By City'], ['Chicago'], ['London'], ['Los Angeles']], selected: "Choose Filter", disabled: "Choose Filter"), {:class => "dropdown", :onchange => "this.form.submit();"}) %>
      <% end %>
      <% if params[:city] %>
        <form action="/salaries/update" method="POST" class="salary-form">
          <h2><%= @salary_presenter.current_city %></h2>
          <table>
            <thead>
              <td><h5>Apprenticeship Length</h5></td>
              <td><h5>Monthly Salary</h5></td>
            </thead>
            <tbody>
              <% @salary_presenter.monthly_salaries_by_location(params["city"]).each do |id, duration, amount| %>
                <tr>
                  <td><label for="<%= duration %>months"><%= duration %> Months</label></td>
                  <td><%= @salary_presenter.current_city_currency_symbol  %> <input type="text" name="monthly[<%= params["city"] %>][<%= duration %>]" value="<%= amount %>"/></td>
                  <td><%= link_to "Delete", destroy_salary_path(id), :class => "button secondary", method: :delete, data: {confirm: "Are you sure you want to delete this salary?"}  %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="row">
            <p>
              <label for="<%= @salary_presenter.current_city %>-annual-starting">Annual Starting Craftsman Salary</label>
            </p>
            <%= @salary_presenter.current_city_currency_symbol  %> <input type="text" name="annual[<%= @salary_presenter.current_city %>]" value="<%= @salary_presenter.annual_salaries_by_location[params["city"]] %>" />
          </div>
          <div class="row">
            <input type="submit" id="update-salaries" class="button primary" value="Update Salaries">
          </div>
        <% end %>
      </div>
    </form>
  </div>
</div>
</div>